version: '3'

services:
  koa:
    container_name: koa
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/opt/app
    depends_on:
      - couchdb
  couchdb:
    container_name: couchdb
    image: couchdb:1.7.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: my_admin_password
    ports: 
      - 5984:5984